### ISSUE TITLE
3DFuse, Dreamfusion3d and Point-E

### ISSUE THREAD

**Issue by jtydhr88** [jtydhr88/sd-webui-txt-img-to-3d-model#10]
May make:
https://dreamfusion3d.github.io/
https://github.com/KU-CVLAB/3DFuse
https://github.com/openai/point-e
as alternative generator engines?

**Comment by AugmentedRealityCat** [comment]
3DFuse gives the best results from what I've seen online, and I think their use of NERF as an intermediary is brilliant, but I haven't tried it. 

Dreamfusion is also looking very good, but I haven't had the opportunity to test that yet either.

I did some extensive testing of point-e last winter and I was underwhelmed by the results even after putting a lot of efforts to make it look OK.

**Comment by gongyifeiisme** [comment]
Threestudio may help you.

**Comment by jtydhr88** [comment]
@gongyifeiisme great! thanks!
https://github.com/threestudio-project/threestudio

**Comment by jtydhr88** [comment]
just want to share some finding here, last week I spent a lot of time on these 3D generator:
1. [3DFuse](https://github.com/KU-CVLAB/3DFuse), on my Linux + P40, I can only generate point clound, never generate 3D obj succuessfully, 
2. [dreamfusion3d.github.io/](https://dreamfusion3d.github.io/) and [threestudio] (https://github.com/threestudio-project/threestudio), threestudio has a great potental ability but I don't think it is good time to ship it to end user,  I tried two cases: first, ran threestudio-dreamfusion3d on my local (Linux + P40), it will cost about unbelievable 40hours, I shut it down, then, I tried it on Google Colab Pro (Tesla T4), even with this G Card, it still needs about 2 hours to generate once. Besides speed issue, currently threestudio only supports Linux (it may support Windows by using WSL2, but I don't give it try)

to be honest, after compared with these, I believe Shap-E is the good choise, at least for now. I will keep my eye on how this field developing.

close this issue for now, but welcome any comments.

**Comment by jtydhr88** [comment]
Dreamfusion:
https://github.com/jtydhr88/sd-webui-txt-img-to-3d-model/assets/860985/5a62f499-6878-4429-92c3-4baf0b7efea5

Threestudio-dreamfusion:

https://github.com/jtydhr88/sd-webui-txt-img-to-3d-model/assets/860985/5559efe3-4ded-4bce-a3a4-45ab112d28b3
