### ISSUE TITLE
Use Threejs to replace Gradio.Model3D preview ?

### ISSUE THREAD

**Issue by jtydhr88** [jtydhr88/sd-webui-txt-img-to-3d-model#11]
According to gradio doc, https://gradio.app/docs/#model3d, I don’t think it has the power that allow me to make “edit“ operations such as “rotate” the generated objects.
Since I built https://github.com/jtydhr88/sd-3dmodel-loader before basing on ThreeJS, I am considering to use it instead of Gradio.Model3D, may allow me to resolve the issues https://github.com/jtydhr88/sd-webui-txt-img-to-3d-model/issues/7, https://github.com/jtydhr88/sd-webui-txt-img-to-3d-model/issues/8, https://github.com/jtydhr88/sd-webui-txt-img-to-3d-model/issues/9

**Comment by AugmentedRealityCat** [comment]
100% - do that ! 
And link your Canvas as well to take renders from your 3d model loader and compositing them together, and with characters !

Nice to have features for the future: depthmap, alpha and normalmap output to be sent to ControlNet.

**Comment by FernandoConti** [comment]
I would use Babylon.js it's SUCH an improvement over Three.js, easy to script, large user base and fast support from the creators.

**Comment by jtydhr88** [comment]
I implemented a new extension for webui https://github.com/jtydhr88/sd-webui-3d-editor, which including 3d modeling features.
I will add a feature to communite to this new extension from here

**Comment by jtydhr88** [comment]
I added a select and button to open the generated obj into 3D editor extension, then you can modity model inside the editor
