### ISSUE TITLE
text300M isn't being cached and gets downloaded on every restart of the UI

### ISSUE THREAD

**Issue by hounddogie** [jtydhr88/sd-webui-txt-img-to-3d-model#13]
As the title says, the model gets redownloaded for first time prompts.

Is this normal behavior?

If this is normal, how may this be mended to where I can store models locally and it utilize them?

A quick glance at download.py looks like they should be cached.

**Comment by jtydhr88** [comment]
I think you have some custom clean up works for your webui git repo on startup, because Sharp-E will download its models into the webui root directory.

**Comment by jtydhr88** [comment]
it should be here
![image](https://github.com/jtydhr88/sd-webui-txt-img-to-3d-model/assets/860985/6c4fe456-5d7b-4d66-8979-952e70c5afb4)

**Comment by hounddogie** [comment]
Thank you good sir.
