### ISSUE TITLE
Doesnt load in auto1111

### ISSUE THREAD

**Issue by TheBitcoinBaron** [jtydhr88/sd-webui-txt-img-to-3d-model#17]
Gives errors like in image below: 
![image](https://github.com/jtydhr88/sd-webui-txt-img-to-3d-model/assets/27411279/88b59df6-2cae-47cf-8796-049a70037317)

**Comment by zeusout11** [comment]
Same here in Vlad1111. It's probably worth mentioning I'm using hard links to save on space
![image](https://github.com/jtydhr88/sd-webui-txt-img-to-3d-model/assets/3880719/2ed80685-bd65-471c-b16d-6c19096fea84)

**Comment by jtydhr88** [comment]
Hey guys, can you help me doing one thing? Just create the folder “outputs” manually inside the extension? Thanks!

**Comment by zeusout11** [comment]
I thought I tried that first, but turns out I made that in the models folder rather than the extensions folder. I'm honestly not sure what I was thinking, but the error didn't show up when I made that folder in the correct place. Thanks!

**Comment by jtydhr88** [comment]
@zeusout11 thanks! I will send a fix to create this folder automatically
