### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by crwpw** [jtydhr88/sd-webui-txt-img-to-3d-model#2]
![1](https://github.com/jtydhr88/sd-webui-txt-img-to-3d-model/assets/13091768/5b4ff402-961b-4570-ae26-34fbea351145)

Even UI is not available, (I've restarted UI several times, also I restarted SD, I even tryed to update all of it... And - nothing, silence...

**Comment by jtydhr88** [comment]
@crwpw can you check is any error log on your console?

**Comment by crwpw** [comment]
> @crwpw can you check is any error log on your console?

unfortunately I've already deleted him 😐

**Comment by jtydhr88** [comment]
can you go to extensions folder and delete this extension and try to reinstall from Avaviable tab?

**Comment by jtydhr88** [comment]
If you still want to try this extension, you can refer to https://github.com/jtydhr88/sd-webui-txt-img-to-3d-model/issues/3

**Comment by jtydhr88** [comment]
Since no more information come, I will close it for now, just feel free to reopen if you still face it and could provide more details for me

**Comment by killakrust** [comment]
Certainly generates a 3d file, but the files it generated for me had insane amounts of polygons, the resulting OBJ was 6.5MB. Is there any way to to control the output size? I tried using the TXT to 3d and IMG to 3d; I had to give up on the IMG to 3d as it was still chugging along 25 minutes later (perhaps a 3070 8GB is not enough vram).

I saw there are additional tabs on the screenshots, but those don't appear for me in Auto1111. Is this where I should be able to have some more conrtol?

**Comment by jtydhr88** [comment]
hi @killakrust , yes, according OpenAI API, there are more control params, I opened an issue https://github.com/jtydhr88/sd-webui-txt-img-to-3d-model/issues/4.
About time spent, to be honest, it is wired for meon my 2070 as well, sometime is fast (about 3 ~ 4 mins), sometime is slow as you (up to 1 hour), may need to optimze the OpenAI code to resolve this issue

**Comment by killakrust** [comment]
Thanks for the reply @jtydhr88, I'll keep my eye on any updates.

I suspect it was partly my own doing. I used an image that had quite a complex background. I tried a smplified version (results were not great, but was faster at least). I think that keeping the TXT prompt simple is also key to keep it from taking too long to process.

**Comment by jtydhr88** [comment]
wow, for the img to 3d, as OpenAI mentioned, it is best has no backgrond from your init image, see here 
![image](https://github.com/jtydhr88/sd-webui-txt-img-to-3d-model/assets/860985/0bfe5f49-5469-4de4-a872-2e7ea8d4b43f)
and 
https://github.com/openai/shap-e
